# Generated by Django 2.2.1 on 2019-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlmodel',
            options={'ordering': ('-published_date',)},
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='token',
            field=models.CharField(default=None, max_length=6, primary_key=True, serialize=False),
        ),
    ]
