# Generated by Django 2.2.1 on 2019-07-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0002_auto_20190708_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='hit_count',
        ),
    ]
